//
//  CardsWorker.swift
//  HearthStone
//
//  Created by Diego Gomes on 29/04/20.
//  Copyright (c) 2020 Diego Gomes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CardsWorker {
    func fetchCards(request: Cards.FetchCards.Request, success: @escaping (Cards.FetchCards.Response)->(), error: @escaping (String)->()) {
        ServiceLayer.request(route: Router.getCards(request: request), onSuccess: { (response: Cards.FetchCards.Response) in
            success(response)
        }) { (errorMsg) in
            error(errorMsg)
        }
    }
}
