//
//  HomeWorker.swift
//  HearthStone
//
//  Created by Diego Gomes on 25/04/20.
//  Copyright (c) 2020 Diego Gomes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class HomeWorker {
    func fetchFilters(success: @escaping (Home.FetchFilters.Response)->(), error: @escaping (String)->()) {
        ServiceLayer.request(route: Router.getFilters, onSuccess: { (response: Home.FetchFilters.Response) in
            success(response)
        }) { (errorMsg) in
            error(errorMsg)
        }
    }
}
