//
//  HomeInteractor.swift
//  HearthStone
//
//  Created by Diego Gomes on 25/04/20.
//  Copyright (c) 2020 Diego Gomes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic {
  func fetchFilters(request: Home.Something.Request)
}

protocol HomeDataStore {
  
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore {
  var presenter: HomePresentationLogic?
  var worker = HomeWorker()
  
  // MARK: Do something
  func fetchFilters(request: Home.Something.Request) {
    let response = Home.Something.Response()
    presenter?.presentFilters(response: response)
  }
}
