//
//  HomeInteractor.swift
//  HearthStone
//
//  Created by Diego Gomes on 25/04/20.
//  Copyright (c) 2020 Diego Gomes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic {
  func fetchFilters()
}

protocol HomeDataStore {
    var filters: Home.FetchFilters.Response? { get set }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore {
  var filters: Home.FetchFilters.Response?
  var presenter: HomePresentationLogic?
  var worker = HomeWorker()
  
  // MARK: Do something
  func fetchFilters() {
    worker.fetchFilters(success: { [weak self] response in
        guard let self = self else { return }
        self.filters = response
        self.presenter?.presentFilters(response: response)
    }, error: { [weak self] msg in
        guard let _ = self else { return }
    })
  }
}
