//
//  HomeModels.swift
//  HearthStone
//
//  Created by Diego Gomes on 25/04/20.
//  Copyright (c) 2020 Diego Gomes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home {
  // MARK: Use cases
  enum FetchFilters {
    struct Response: Decodable {
        var classes: [String]?
        var sets: [String]?
        var types: [String]?
        var factions: [String]?
        var qualities: [String]?
        var races: [String]?
        var locales: [String]?
    }
    
    struct ViewModel {
        var items: [Item]
    }
    
    struct Item {
        var filterName: String
        var categories: [String]
    }
  }
}
