//
//  HomePresenter.swift
//  HearthStone
//
//  Created by Diego Gomes on 25/04/20.
//  Copyright (c) 2020 Diego Gomes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic {
  func presentFilters(response: Home.Something.Response)
}

class HomePresenter: HomePresentationLogic {
  weak var viewController: HomeDisplayLogic?
  
  func presentFilters(response: Home.Something.Response) {
    let viewModel = Home.Something.ViewModel()
    viewController?.displayFilters(viewModel: viewModel)
  }
}
