//
//  HomeInteractor.swift
//  HearthStone
//
//  Created by Diego Gomes on 25/04/20.
//  Copyright (c) 2020 Diego Gomes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic {
  func fetchFilters()
}

protocol HomeDataStore {
    var selectedCategory: Cards.FetchCards.Request! { get set }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore {
  var selectedCategory: Cards.FetchCards.Request!
  var presenter: (HomePresentationLogic & WorkerPresentationFeedback)?
  var worker = HomeWorker()
  
  // MARK: fetch filters
  func fetchFilters() {
    presenter?.load(showLoader: true)
    worker.fetchFilters(success: { [weak self] response in
        guard let self = self else { return }
        self.presenter?.load(showLoader: false)
        self.presenter?.presentFilters(response: response)
    }, error: { [weak self] msg in
        guard let self = self else { return }
        self.presenter?.load(showLoader: false)
        self.presenter?.showError(message: msg)
    })
  }
}
