//
//  CardsPresenter.swift
//  HearthStone
//
//  Created by Diego Gomes on 29/04/20.
//  Copyright (c) 2020 Diego Gomes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CardsPresentationLogic {
    func displayCards(response: Cards.FetchCards.Response)
}

class CardsPresenter: CardsPresentationLogic {
    weak var viewController: CardsDisplayLogic?
    
    // MARK: Display Cards
    func displayCards(response: Cards.FetchCards.Response) {
//        let viewModel = Cards.FetchCards.ViewModel()
//        viewController?.displayCards(viewModel: viewModel)
    }
}
