//
//  CardsModels.swift
//  HearthStone
//
//  Created by Diego Gomes on 29/04/20.
//  Copyright (c) 2020 Diego Gomes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Cards {
    // MARK: Use cases
    enum FetchCards {
        struct Request {
            var category: String
            var subCategory: String
        }
        struct Response: Decodable {
            var cardID, dbfID, name, cardSet: String?
            var type, faction, rarity: String?
            var health: Int?
            var collectible: Bool?
            var playerClass: String?
            var img: String?
            var imgGold: String?
            var locale: String?
        }
        struct ViewModel {
            var cardImages: [String]
        }
    }
}
