//
//  CardsViewController.swift
//  HearthStone
//
//  Created by Diego Gomes on 29/04/20.
//  Copyright (c) 2020 Diego Gomes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CardsDisplayLogic: class {
    func displayCards(viewModel: Cards.FetchCards.ViewModel)
}

class CardsViewController: UIViewController, CardsDisplayLogic {
    var interactor: CardsBusinessLogic?
    
    // MARK: Setup
    private func setup() {
        let viewController = self
        let interactor = CardsInteractor()
        let presenter = CardsPresenter()
        self.interactor = interactor
        viewController.interactor = interactor
        interactor.presenter = presenter
        presenter.viewController = viewController
    }
    
    // MARK: View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        fetchCards()
    }
    
    // MARK: Fetch Cards
    func fetchCards() {
//        let request = Cards.FetchCards.Request()
//        interactor?.fetchCards(request: request)
    }
    
    func displayCards(viewModel: Cards.FetchCards.ViewModel) {
    }
}
